sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
  # - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in docker-kubernetes-237606-66548918b455.json.enc -out docker-kubernetes-237606-66548918b455.json -d
  #- openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - openssl aes-256-cbc -K $encrypted_69c84c9db1a5_key -iv $encrypted_69c84c9db1a5_iv -in service-deployment.json.enc -out service-deployment.json -d
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - yes | gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-deployment.json
  - gcloud auth list
  - gcloud projects list
  #- gcloud services enable container.googleapi.com
  - gcloud config set project multi-k8s-289408
  - gcloud config set compute/zone europe-west1
  - gcloud container clusters get-credentials multi-k8s --region europe-west1 --project multi-k8s-280408



  
    # Log into GCR
  #- yes | gcloud auth configure-docker
   
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 
  - docker build -t ctl11/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run eu.gcr.io/docker-kubernetes-237606/jsdevtom/react-test npm test -- --coverage
     docker run -e CI=true ctl11/react-test mpm test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
